#!/bin/bash

BASEDIR=$(dirname $0)
source $BASEDIR/billing.sh

BILLING_DATE=201411
BILLING_PREVDATE=201410
GROUPREPORT_DATE=2014-11
NOTIFICATIONS=$BASEDIR/pricing/BillingNotificationContacts.txt

run $BILLING_DATE $BILLING_PREVDATE $GROUPREPORT_DATE #$NOTIFICATIONS

