#!/bin/bash

BASEDIR=$(dirname $0)
source $BASEDIR/billing.sh

BILLING_DATE=201504
BILLING_PREVDATE=201503
GROUPREPORT_DATE=2015-04
NOTIFICATIONS=$BASEDIR/pricing/BillingNotificationContacts.txt

run $BILLING_DATE $BILLING_PREVDATE $GROUPREPORT_DATE #$NOTIFICATIONS

