#!/bin/bash

BASEDIR=$(dirname $0)
source $BASEDIR/billing.sh

BILLING_DATE=201508
BILLING_PREVDATE=201507
GROUPREPORT_DATE=2015-08
NOTIFICATIONS=$BASEDIR/pricing/BillingNotificationContacts.txt

run $BILLING_DATE $BILLING_PREVDATE $GROUPREPORT_DATE #$NOTIFICATIONS

